# Generated by Django 4.0.6 on 2022-07-27 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_artists_people_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='artist_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=25)),
                ('release_date', models.DateField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.artists')),
            ],
        ),
    ]
