# Generated by Django 4.0.6 on 2022-07-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_remove_songs_artist_songs_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artists',
            options={'ordering': ('artist_name',)},
        ),
        migrations.AlterModelOptions(
            name='songs',
            options={'ordering': ('song_name',)},
        ),
        migrations.AddField(
            model_name='songs',
            name='cover',
            field=models.ImageField(default='uploads/default_music.jpeg', upload_to='uploads/'),
        ),
    ]
